"""Load-time pipeline validation (FR-5.3, FR-2.3, PRD §8).

Run once when a pipeline is loaded for a run. Three classes of check:

* **Dangling artifact dataflow** (FR-5.3): every ``inputs:``/``artifact:``
  reference must be a seed artifact (``prd.md``/``plan.md``) or produced by an
  earlier step's ``output:``.
* **Adapter capabilities** (FR-2.3): a step that writes the repo cannot bind an
  adapter that can't (e.g. ``api``); a step that needs a schema *warns* if its
  adapter only does best-effort JSON, and *errors* if it does none.
* **Banned flags** (§8): constructing each referenced adapter runs the
  permission-bypass / hook-disabling lint; a violation aborts the load.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from gauntlet.config import BannedFlagError
from gauntlet.engine.config import RunConfig
from gauntlet.engine.execution import get_spec
from gauntlet.engine.pipeline import Pipeline, Step
from gauntlet.engine.steptypes import HUMAN_RESPONSE_ARTIFACT

SEED_ARTIFACTS = frozenset({"prd.md", "plan.md"})


class PipelineValidationError(ValueError):
    def __init__(self, errors: list[str]) -> None:
        super().__init__("pipeline failed validation:\n- " + "\n- ".join(errors))
        self.errors = errors


@dataclass
class ValidationReport:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def ok(self) -> bool:
        return not self.errors


def validate_pipeline(
    pipeline: Pipeline, config: RunConfig, *, seeds: frozenset[str] = SEED_ARTIFACTS
) -> ValidationReport:
    report = ValidationReport()
    available: set[str] = set(seeds)
    for stage in pipeline.stages:
        stage_ids = {step.id for step in stage.steps}
        for step in stage.steps:
            _validate_step(step, config, available, report)
            # on_fail routing is stage-local: the runtime jumps within the
            # current stage's step list, so a cross-stage target would validate
            # then crash at runtime (review F-005). Reject it at load.
            if step.on_fail and step.on_fail.route_to not in stage_ids:
                report.errors.append(
                    f"step {step.id!r} on_fail routes to {step.on_fail.route_to!r}, "
                    "which is not a step in the same stage (cross-stage routing "
                    "is unsupported, FR-5.4 / review F-005)"
                )
            output = step.get("output")
            if output:
                available.add(output)
            if step.type == "adversarial_cycle":
                # the cycle registers its round outputs as named artifacts
                available.update({"findings.json", "triage.json", "confirm.json"})
    if report.errors:
        raise PipelineValidationError(report.errors)
    return report


def _validate_step(
    step: Step, config: RunConfig, available: set[str], report: ValidationReport
) -> None:
    # 1. step type resolves
    try:
        spec = get_spec(step.type)
    except KeyError as exc:
        report.errors.append(str(exc))
        return

    # 1b. `max_turns` is unenforceable on the pinned CLIs (claude 2.1.172 has no
    # --max-turns; codex exec has no turn cap) — reject it rather than silently
    # ignore a claimed guard (review F-006). timeout_s + budget_usd are the
    # working per-step halts (FR-3.3).
    if step.max_turns is not None:
        report.errors.append(
            f"step {step.id!r} sets max_turns, but no installed adapter can honor "
            "it; use timeout_s / budget_usd (FR-3.3 / review F-006)"
        )

    # 1c. reserve the synthetic human-response artifact name (review F-002).
    # `--response` resumes inject the human-decision history under exactly
    # `human-response.md` into an invocation-local copy of the step's inputs. A
    # pipeline that ALSO declares that name (as an input, output, or artifact)
    # collides: the synthetic file would silently replace the declared one and
    # rendering would emit two identically-named blocks, breaking FR-4's
    # single-artifact / single-block premise. Fail closed at load.
    declared_reserved = [
        f"input {HUMAN_RESPONSE_ARTIFACT!r}"
        for name in (step.get("inputs", []) or [])
        if name == HUMAN_RESPONSE_ARTIFACT
    ] + [
        f"{field} {HUMAN_RESPONSE_ARTIFACT!r}"
        for field in ("output", "artifact")
        if step.get(field) == HUMAN_RESPONSE_ARTIFACT
    ]
    for where in declared_reserved:
        report.errors.append(
            f"step {step.id!r} {where} collides with the engine's reserved "
            "synthetic human-response artifact: that name is generated by a "
            "`--response` resume and must not be declared by a pipeline "
            "(FR-4 / review F-002); choose another name"
        )

    # 2. dangling artifact dataflow (FR-5.3)
    for name in (step.get("inputs", []) or []):
        if name not in available:
            report.errors.append(
                f"step {step.id!r} input {name!r} is not a seed artifact and is "
                "produced by no earlier step (dangling reference, FR-5.3)"
            )
    artifact = step.get("artifact")
    if artifact and artifact not in available:
        report.errors.append(
            f"step {step.id!r} artifact {artifact!r} is not available at this "
            "point (dangling reference, FR-5.3)"
        )

    # 2b. adversarial_cycle role bindings (FR-5.2): the three core roles are
    # required, and capability checks are role-aware — the FIXER writes the
    # repo (FR-2.3); the REVIEWER is intended read-only (FR-9.6), so a
    # repo-write check on it would be exactly backwards.
    if step.type == "adversarial_cycle":
        for role in ("reviewer", "triager", "fixer"):
            if not step.get(role):
                report.errors.append(
                    f"step {step.id!r} (adversarial_cycle) is missing required "
                    f"role {role!r} (FR-5.2)"
                )
        fixer = step.get("fixer")
        if fixer and fixer in config.agents:
            if not config.profile(fixer).capabilities().repo_write:
                report.errors.append(
                    f"step {step.id!r} fixer {fixer!r} cannot write the repo "
                    "(FR-2.3): fix rounds edit files"
                )
        if step.get("commit_each_fix_round") is False:
            report.errors.append(
                f"step {step.id!r} sets commit_each_fix_round=false, which "
                "breaks the clean-handoff invariant (FR-9.3/9.4); unsupported"
            )

    # 2c. retrospective role bindings (FR-6.2): at least one self-critiquing
    # agent is required; the proposer is optional (no proposer → self-critique
    # only, generation skipped and recorded).
    if step.type == "retrospective":
        if not (step.get("agents") or []):
            report.errors.append(
                f"step {step.id!r} (retrospective) needs a non-empty `agents:` "
                "list to self-critique (FR-6.2)"
            )

    # 3. agent profile resolution + capabilities (FR-2.3) + banned flags (§8)
    agent_refs = _agent_refs(step, spec.needs_agent)
    for ref in agent_refs:
        if ref not in config.agents:
            report.errors.append(
                f"step {step.id!r} references undefined agent profile {ref!r}"
            )
            continue
        profile = config.profile(ref)
        if profile.max_turns is not None:
            report.errors.append(
                f"agent profile {ref!r} sets max_turns, unenforceable on the "
                "pinned CLIs; use step_timeout_s / budget_usd (review F-006)"
            )
        caps = profile.capabilities()
        if spec.step_requires_repo_write(step) and not caps.repo_write:
            report.errors.append(
                f"step {step.id!r} needs repo-write but agent {ref!r} "
                f"(adapter {profile.adapter!r}) cannot write the repo (FR-2.3)"
            )
        if _step_uses_schema(step, spec):
            if caps.structured_output == "none":
                report.errors.append(
                    f"step {step.id!r} needs structured output but agent {ref!r} "
                    "supports none (FR-2.3)"
                )
            elif caps.structured_output == "best_effort":
                report.warnings.append(
                    f"step {step.id!r} relies on schema output but agent {ref!r} "
                    "is best-effort JSON only; validate-and-retry applies (FR-2.3)"
                )
        try:
            profile.build_adapter()
        except BannedFlagError as exc:
            report.errors.append(
                f"step {step.id!r} agent {ref!r} uses a banned flag: {exc}"
            )
        except Exception as exc:  # construction issues surface as warnings
            report.warnings.append(
                f"step {step.id!r} agent {ref!r} could not be pre-constructed "
                f"({exc}); deferred to runtime"
            )


def _agent_refs(step: Step, needs_agent: bool) -> list[str]:
    refs: list[str] = []
    if step.agent:
        refs.append(step.agent)
    for key in ("message_agent", "reviewer", "triager", "fixer", "confirmer",
                "escalation_agent", "proposer"):
        ref = step.get(key)
        if ref:
            refs.append(ref)
    # The retrospective step fans out over a list of self-critiquing agents
    # (FR-6.2); each must resolve to a profile like any other agent reference.
    for ref in step.get("agents", []) or []:
        refs.append(ref)
    return refs


def _step_uses_schema(step: Step, spec) -> bool:
    return bool(spec.uses_schema or step.get("findings_schema") or step.get("schema"))
